# Generated by Django 6.0.2 on 2026-02-23 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="body",
        ),
        migrations.RemoveField(
            model_name="article",
            name="photo",
        ),
    ]
