# Generated by Django 6.0.2 on 2026-02-23 21:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0002_remove_article_body_remove_article_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="body",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="article",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
        migrations.AddField(
            model_name="article",
            name="summary",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="title",
            field=models.CharField(default="Untitled", max_length=150),
            preserve_default=False,
        ),
    ]
