# Generated by Django 6.0.2 on 2026-02-27 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0003_article_body_article_date_article_photo_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="body",
        ),
    ]
