# Generated by Django 6.0.2 on 2026-02-27 23:04

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0004_remove_article_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="body",
            field=ckeditor.fields.RichTextField(default=""),
            preserve_default=False,
        ),
    ]
